name: Cập nhật các kỳ quay theo lịch

on:
  workflow_dispatch:
  schedule:
    - cron: "7,27,47 6,11,14 * * *"
    - cron: "17 15 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    uses: ./.github/workflows/update-dataset.yml
    with:
      products: mega645 power655 lotto535 max3d max3dpro
      report_name: scheduled
