name: Cập nhật Keno và Bingo18

on:
  workflow_dispatch:
  schedule:
    - cron: "5,15,25,35,45,55 0-14,23 * * *"
    - cron: "5,25,45 15 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    uses: ./.github/workflows/update-dataset.yml
    with:
      products: keno bingo18
      report_name: fast
